#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "oskarrough"
email = "oskar@rough.dk"

[revsets]
# A bit more verbose compared to default log, to see whats up
log = "present(@) | ancestors(immutable_heads().., 6) | ancestors(heads(tracked_remote_bookmarks()), 6) | trunk()"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[ui]
default-command = "log" # This way `jj` logs for you, handy
diff-formatter = ":git"

[remotes.origin]
auto-track-bookmarks = "*"
# auto-track-created-bookmarks = "*"

# [remotes.upstream]
# auto-track-bookmarks = "*"
