#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "oskarrough"
email = "oskar@rough.dk"

[revsets]
log = "present(@) | ancestors(immutable_heads().., 2) | ancestors(heads(remote_bookmarks()), 2) | trunk()"
