# Window
window_padding_width 0
hide_window_decorations yes
confirm_os_window_close -1

# Aesthetics
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# font_family JetBrains Mono
# font_family Input
# font_family Iosevka Term
font_size 14.0

# BEGIN_KITTY_FONTS
font_family      family='Iosevka Term' style=Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
# Keybindings
map shift+enter send_text all \e\r
map cmd+enter new_os_window
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

